version: '3.7'
services:
    back:
        container_name: areabackend
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/backend
        ports:
            - '8080:8080'